// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbrekpckwmxsewycwmki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicmVrcGNrd214c2V3eWN3bWtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjExNzUsImV4cCI6MjA2NTYzNzE3NX0.vn8Uy4labC_u8Kdpo7jxI_aGCFQiPDHsRuhKZny6igg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);